<?php

namespace PrivlinkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * privlinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class privlinkRepository extends EntityRepository
{
}
