privlink:
    resource: "@PrivlinkBundle/Controller/"
    type:     annotation
    prefix:   /

privlink:
    pattern: /
    defaults: {_controller: PrivlinkBundle:privlink:new}

hidden:
    pattern: /hidden/{hash}
    defaults: {_controller: PrivlinkBundle:hidden:index}
