privlink:
    resource: "@PrivlinkBundle/Controller/"
    type:     annotation
    prefix:   /

privlink:
    pattern: /
    defaults: {_controller: PrivlinkBundle:privlink:new}

hidden:
    pattern: /{hash}
    defaults: {_controller: PrivlinkBundle:hidden:index}

save_link:
    pattern: /save/{hash}
    defaults: {_controller: PrvlinkBundle:default:save}

about:
    pattern: /info/about/
    defaults: {_controller: PrivlinkBundle:default:about}

faq:
    pattern: /info/faq/
    defaults: {_controller: PrivlinkBundle:default:faq}

